version: '3.7'




services:


  naming-server:
    image: roshan66/rmd-naming-server:0.0.1-SNAPSHOT
    mem_reservation: 700m
    ports:
      - "8761:8761"
    networks:
      - currency-network



  zipkin-server:
    image: openzipkin/zipkin:2.23
    mem_reservation: 300m
    ports:
      - "9411:9411"
    depends_on:
      - rabbitmq
    environment:
      RABBIT_URI: amqp://guest:guest@rabbitmq:5672
    restart: always


  rabbitmq:
    image: rabbitmq:3.11.6-management-alpine
    mem_reservation: 300m
    ports:
      - "5672:5672"
      - "15672:15672"
    networks:
      - currency-network





  currency-exchange:
    image: roshan66/rmd-currency-exchange-service:0.0.1-SNAPSHOT
    mem_reservation: 700m
    ports:
      - "8000:8000"
    networks:
      - currency-network
    depends_on:
      - naming-server
      - rabbitmq
    environment:
     EUREKA.CLIENT.SERVICEURL.DEFAULTZONE: http://naming-server:8761/eureka
     SPRING.ZIPKIN.BASEURL: http://zipkin-server:9411/
     RABBIT_URI: amqp://guest:guest@rabbitmq:5672
     SPRING_RABBITMQ_HOST: rabbitmq
     SPRING_ZIPKIN_SENDER_TYPE: rabbit



  currency-conversion:
       image: roshan66/rmd-currency-conversion-service:0.0.1-SNAPSHOT
       mem_reservation: 700m
       ports:
         - "8100:8100"
       networks:
         - currency-network
       depends_on:
         - naming-server
         - rabbitmq
       environment:
         EUREKA.CLIENT.SERVICEURL.DEFAULTZONE: http://naming-server:8761/eureka
         SPRING.ZIPKIN.BASEURL: http://zipkin-server:9411/
         RABBIT_URI: amqp://guest:guest@rabbitmq:5672
         SPRING_RABBITMQ_HOST: rabbitmq
         SPRING_ZIPKIN_SENDER_TYPE: rabbit


  api-gateway:
         image: roshan66/rmd-api-gateway:0.0.1-SNAPSHOT
         mem_reservation: 700m
         ports:
           - "8765:8765"
         networks:
           - currency-network
         depends_on:
           - naming-server
           - rabbitmq
         environment:
           EUREKA.CLIENT.SERVICEURL.DEFAULTZONE: http://naming-server:8761/eureka
           SPRING.ZIPKIN.BASEURL: http://zipkin-server:9411/
           RABBIT_URI: amqp://guest:guest@rabbitmq:5672
           SPRING_RABBITMQ_HOST: rabbitmq
           SPRING_ZIPKIN_SENDER_TYPE: rabbit


networks:
  currency-network:





